# 端口号
server:
  port: 9001

spring:
  application:
    name: config-server # 应用名称
  # profiles.active: native # 本地配置文件需要添加此属性
  # Cloud配置
  cloud:
    # Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # Config
    config:
      server:
        git:
          uri: https://github.com/Nousin-Tang/SpringCloudProject.git
          search-paths: configfile # 如果项目中没有二级文件夹,则将引入全部配置文件,有文件夹则需添加文件夹路径，多个以","分开
          username:
          password:
        # native.search-locations: file:/usr/local/config/
