
server:
  port: 9101


nousin:
  base:
    requestUrl: /order
  jwt:
    signKey: 123456
  feign:
    server:
      account: account-server
      storage: storage-server
    ok-http:
      connect-timeout: 60
      read-timeout: 60
      write-Timeout: 120
  server:
    auth: auth-service

# Spring
spring:
  # 应用名称
  application:
    name: order-service
  # 数据库配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

feign:
  # feign启用hystrix，才能熔断、降级
  # hystrix:
  # enabled: true
  # 启用 okhttp 关闭默认 httpclient
  httpclient:
    enabled: false #关闭httpclient
    # 配置连接池
    max-connections: 200 #feign的最大连接数
    max-connections-per-route: 50 #fegin单个路径的最大连接数
  okhttp:
    enabled: true
  # 请求与响应的压缩以提高通信效率
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true


#security:
#  oauth2:
#    client:
#      client-id: browser
##      client-secret: clientsecret
#      user-authorization-uri:  http://127.0.0.1:9101/oauth/authorize
#      access-token-uri:  http://127.0.0.1:9101/oauth/token
#    resource:
#      jwt:
#        key-uri:  http://127.0.0.1:9101/oauth/token_key

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      grant-type: refresh_token,password
      scope: all
      accessTokenUri: lb://${nousin.server.auth}/oauth/token
      userAuthorizationUri: lb://${nousin.server.auth}/oauth/authorize
      access-token-validity-seconds: 7200
      clientAuthenticationScheme: form
    resource:
      jwt:
        key-uri: lb://${nousin.server.auth}/oauth/token_key

