
server:
  port: 9101

# Spring
spring:
  # 应用名称
  application:
    name: order-service
  # 数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


security:
  oauth2:
    client:
      client-id: browser
#      client-secret: clientsecret
      user-authorization-uri:  http://127.0.0.1:9101/oauth/authorize
      access-token-uri:  http://127.0.0.1:9101/oauth/token
    resource:
      jwt:
        key-uri:  http://127.0.0.1:9101/oauth/token_key

hello.word: nihao
