server:
  port: 9002

# Spring
spring:
  # 应用名称
  application:
    name: auth-service
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848 # Nacos
  # 数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


nousin:
  base:
    requestUrl: /auth
  jwt:
    signKey: 123456
    validity-seconds: 7200

  oauth2-client:
      clientId: client
      clientSecret: secret
      grantType: refresh_token,password
      scope: all